services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=#Maluko1998
    ports:
      - "14330:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass "#Maluko1998"
    restart: unless-stopped

volumes:
  sqlserver-data:
  redis-data:
