USE[GLOBAL]
GO

DROP TABLE IF EXISTS CLIENT;
GO

CREATE TABLE CLIENT (
Id INT PRIMARY KEY IDENTITY(1,1),
IsActive BIT DEFAULT  1,
Name VARCHAR(200),
Email VARCHAR(200),
Phone VARCHAR(20),
CreatedAt DATETIME DEFAULT GETDATE()
)


CREATE INDEX IDX_NAME_INC_EMAIL_PHONE_CREATEDAT ON CLIENT(Name) INCLUDE(Email,Phone,CreatedAt,isactive)

CREATE INDEX IDX_Email_INC_EMAIL_PHONE_CREATEDAT ON CLIENT(Email) INCLUDE(Name,Phone,CreatedAt,isactive)