USE[GLOBAL]
GO

DROP TABLE IF EXISTS PRODUCT;
GO

CREATE TABLE PRODUCT (
Id INT PRIMARY KEY IDENTITY(1,1),
IsActive BIT DEFAULT 1,
Name VARCHAR(200),
Description VARCHAR(MAX),
Price DECIMAL(10,2),
StockQuantity INT
)


CREATE INDEX IDX_NAME_INC_DESCRIPTION_PRICE_STOCKQUANTITY ON PRODUCT(Name) INCLUDE(Description,Price,StockQuantity,isactive)
