USE [GLOBAL]
GO

DROP TABLE IF EXISTS Orders
GO

CREATE TABLE Orders (
    [Id] INT IDENTITY(1,1) PRIMARY KEY,
    ClientId INT NOT NULL,
    PriceOrder decimal(10,2),
    Status INT,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE INDEX IDX_CLIENTID_INCL_PRICEORDER_CREATEDAT ON ORDERS(CLIENTID) INCLUDE(PRICEORDER,CREATEDAT,STATUS)
GO

ALTER TABLE ORDERS
ADD CONSTRAINT FK_CLIENTID
FOREIGN KEY (CLIENTID)
REFERENCES CLIENT(Id)
GO