USE [GLOBAL]
GO

DROP TABLE IF EXISTS OrderItem
GO

CREATE TABLE OrderItem (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    OrderId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(10,2)
);
GO

CREATE INDEX IDX_ORDERID_INCL_PRODUCTID_QUANTITY_PRICE ON OrderItem(ORDERID) INCLUDE(PRODUCTID,QUANTITY,PRICE)
GO

CREATE INDEX IDX_PRODUCTID_INCL_ORDERID_QUANTITY_PRICE ON OrderItem(PRODUCTID) INCLUDE(ORDERID,QUANTITY,PRICE)
GO

ALTER TABLE OrderItem
ADD CONSTRAINT FK_PRODUCTID
FOREIGN KEY (PRODUCTID)
REFERENCES PRODUCT(Id)
GO

ALTER TABLE OrderItem
ADD CONSTRAINT FK_ORDERID
FOREIGN KEY (ORDERID)
REFERENCES ORDERS(Id)
GO